app.rb
bin/deploy
lib/document/frontmatter.rb
lib/document/markdown.rb
tests/document/frontmatter.rb

This PR corrects small typos or bugs across several files.
This PR should be merged before #3

Small refactorings

---

Gemfile
README.md

This PR updates the README to add an explanation of the project and how to run it.

Update README to add an explanation of the project

---

public/stylesheets/sass/_bootstrap.scss
public/stylesheets/sass/_buttons.scss
public/stylesheets/sass/_mixins.scss
public/stylesheets/sass/_page-section.scss
public/stylesheets/sass/_person.scss
public/stylesheets/sass/_social.scss
public/stylesheets/sass/_variables.scss
public/stylesheets/sass/main.scss
tests/web/person.rb
views/_social.erb
views/person.erb

Styling for person profile page and shared social widget

---

app.rb
public/stylesheets/sass/_buttons.scss
public/stylesheets/sass/_search.scss
public/stylesheets/sass/_site-header.scss
public/stylesheets/sass/main.scss
tests/web/search.rb
views/search.erb

^ screenshot by @zarino :smiley:

Add a very basic search page

---

.gitignore
lib/ep/person.rb
lib/page/place.rb
tests/ep/person.rb
tests/page/place.rb
tests/web/event.rb
tests/web/events.rb
tests/web/layout.rb
tests/web/state.rb
views/place.erb

Fix some of the coveralls red lines

Improve coveralls

---

tests/ep/people_by_legislature.rb
tests/ep/person.rb
tests/fixtures/ep_data/1e00ca8/ep-popolo-v1.0.json
tests/fixtures/ep_data/99f866a/ep-popolo-v1.0.json
tests/fixtures/ep_data/d96d2be/countries.json
tests/page/place.rb
tests/test_helper.rb
tests/web/representatives.rb
tests/web/senators.rb

This PR updates the EP fixtures so that we have the version with emails and with [this changes](https://github.com/everypolitician-scrapers/nigeria-national-assembly/pull/11).

Add fixtures with emails

---

README.md

Tiny PR to add badges to the README

Add Travis and Coveralls badges to README

---

app.rb
lib/membership_csv/people.rb
lib/page/place.rb
tests/membership_csv/people.rb
tests/page/place.rb
tests/web/person.rb
tests/web/state.rb
views/place.erb

This is a previous cleaning step before dealing with showing all people in child areas on a State page.

Cleaning before state page

---

.travis.yml
bin/prepare-data
lib/document/markdown_with_frontmatter.rb
lib/page/homepage.rb
tests/document/markdown_with_frontmatter.rb
tests/page/homepage.rb
tests/page/person.rb
tests/test_doubles.rb

This PR splits the PR that removes the hardcoded people from the homepage and contains only the commits that were about refactoring/tidying up.
Merge after #98

Refactorings before featured people

---

Gemfile
Gemfile.lock

While investigating #62 this made my eyes bleed and it is an easy fix.
Fixes #119

Remove compass dependency since we are now using bootstrap

---

.travis.yml
app.rb
lib/ep/people_by_legislature.rb
lib/ep/person.rb
lib/membership_csv/people.rb
lib/membership_csv/person.rb
tests/ep/people_by_legislature.rb
tests/ep/person.rb
tests/membership_csv/people.rb
tests/membership_csv/person.rb
tests/page/person.rb
tests/shared_examples/people_interface_test.rb
tests/web/constituency.rb
tests/web/district.rb
tests/web/governors.rb
tests/web/homepage.rb
tests/web/person.rb
tests/web/representatives.rb
tests/web/senators.rb
tests/web/state.rb
views/homepage.erb

Use human-friendly person slugs instead of person ids in person urls
Basically this PR is about changing a lot of test expectations :laughing: 
:snail: :snail:

Person slugs 

---

.travis.yml

Designers are going to need them for #130

Update prepare-data commit in travis so that designers have fixed tables

---

app.rb
tests/web/constituency.rb
tests/web/district.rb
tests/web/homepage.rb
tests/web/person.rb
tests/web/state.rb
views/homepage.erb

As part of EiE feedback, this PR reduces the size of the Twitter widget in the homepage.
It also corrects the twitter handle in the settings, uses it on the widget and adds tests.
Part of #112

Reduce twitter widget size

---

public/stylesheets/sass/_person.scss
views/_footer.erb
views/_head.erb
views/homepage.erb

Small fixes

---

bin/deploy
views/_analytics.erb
views/_head.erb
views/layout.erb

The tracking code was taken from the Pombola version of the site.
The JavaScript code was taken from Google's official documentation:
https://developers.google.com/analytics/devguides/collection/analyticsjs/
Closes #127

Add Google analytics

---

tests/web/constituency.rb
tests/web/place.rb

This will come in handy for the redirects PR
Merge before #141

Move generic tests in constituency test file to a generic test file

---

public/stylesheets/sass/_tables.scss
public/stylesheets/sass/main.scss

Apply Bootstrap styling to markdown tables

---

lib/ep/person.rb
lib/membership_csv/people.rb
tests/ep/people_by_legislature.rb
tests/ep/person.rb
tests/featured_person.rb
tests/membership_csv/people.rb
tests/membership_csv/person.rb
tests/page/person.rb
tests/test_doubles.rb

This PR does some cleaning needed for the person factory PR

Clean before factories

---

.github/CONTRIBUTING.md
.github/PULL_REQUEST_TEMPLATE.md
.github/code-of-conduct.md
.github/design-decisions.md
README.md

This PR adds a contributing guide, a PR template, an explanation of the design, some tribal knowledge and a code of conduct.
Closes #74

Add contributing guide

---

app.rb
lib/page/homepage.rb
public/stylesheets/sass/_homepage.scss
tests/page/homepage.rb
tests/web/homepage.rb
views/homepage.erb

Remove Quote of the Week from homepage

---

public/stylesheets/sass/_site-footer.scss
views/_footer.erb

Simplify footer to reduce "About" content duplication
