theyworkforyou/shineyoureye-sinatra

.travis.yml, app.rb, lib/document/document.rb, lib/document/frontmatter.rb, lib/document/frontmatter_parser.rb, lib/document/markdown.rb, lib/document/markdown_parser.rb, lib/document/markdown_with_frontmatter.rb, tests/document/frontmatter.rb, tests/document/frontmatter_parser.rb, tests/document/markdown.rb, tests/document/markdown_parser.rb, tests/document/markdown_with_frontmatter.rb, tests/test_helper.rb
The document classes needed a bit of attention as they were made in a bit of a rush.
This PR refactors some of the code, basically:
* Makes the markdown and frontmatter parsers take the contents of the file to parse as an argument in the constructor, instead of each of them opening the same file (plus the document class which was also opening it)! Now the file is opened once, in the document class, and its contents passed to Markdown and Frontmatter.
* Renames the document class to `MarkdownWithFrontmatter` as suggested by Mark, and also renames `Markdown` and `Frontmatter` to `MarkdownParser` and `FrontmatterParser`. Hopefully with this we have more of a DSL.
* The date class member was refactored into a method which allows to remove that logic from the constructor. Also, a test was …
=> Refactor the Document classes

.travis.yml, Gemfile, Gemfile.lock, app.rb, lib/document/markdown_with_frontmatter.rb, lib/helpers/constants_helper.rb, lib/page/post.rb, lib/page/posts.rb, tests/document/markdown_with_frontmatter.rb, tests/fixtures/ep_data/75b7651/ep-popolo-v1.0.json, tests/fixtures/ep_data/d8a4682/countries.json, tests/page/post.rb, tests/page/posts.rb, tests/test_helper.rb, tests/web/post.rb, tests/web/posts.rb, views/post.erb, views/posts.erb
This PR updates the views in the blog and single blog post so that they use the markup and css classes used in the Jekyll version of the site.
In the way to achieve that, it also adds a convenient class to find markdown files in specific folders, a functionality that will be needed for the rest of content subfolders inside the prose folder.
Finally, it stubs the http requests made to github so that the web tests don't force you to be connected to the internet for them to pass.
=> Update blog views

.travis.yml, bin/deploy, lib/page/info.rb, tests/page/info.rb
The deploy script can now be passed an argument so that we can
git checkout a specific SHA in the content repository after cloning it,
and before symlinking the media files.
This is done so that the tests can be run at a specific sha of the
prose repository, in order to get predictable test output.
=> Let the deploy script use a specific version of content from prose.io

.travis.yml, README.md, Rakefile
The Rakefile was simplified leaving only a task that runs all the tests as specified in the `default` task definition. This allows to run all the tests as `bundle exec rake test`
=> Simplify rakefile

lib/page/post.rb
`BASEURL` was quoted in the post page.
=> Small bugfix for the BASEURL constant being quoted needlessly

app.rb, lib/helpers/constants_helper.rb, lib/page/info.rb, tests/page/info.rb, tests/web/info.rb, views/info.erb
This PR adds a generic presenter page for all info pages (static pages) and the corresponding route and view.
For now this is a working solution for the pages that currently exist under `prose/info/`, which don't contain the date in the filename. The presenter is searching for files with a pattern of `"#{directory}/#{slug}.md"`. If new pages are added, prose will include the date in the filename when saving. There doesn't seem to be a way to tell prose to enable/disable the date in the filename, so I have raised an issue with them just in case. - **Update:** They have confirmed it is not possible.
- If you don't provide a `title` field in the frontmatter, the `title` text field in the prose editor will show the full file path, for example:
`posts/2017-01-12-your-filename.md`, which you …
=> Add Info pages

app.rb, lib/page/info.rb, lib/page/post.rb, lib/page/posts.rb, tests/document/markdown_with_frontmatter.rb, tests/page/info.rb, tests/page/post.rb, tests/page/posts.rb
This PR makes two small additions:
1) Moves the knowledge of the route from pages to where the route is defined
2) Adds a test to document the case when filenames don't include the date
=> Refactorings

app.rb, lib/document/finder.rb, lib/helpers/constants_helper.rb, lib/page/info.rb, lib/page/post.rb, lib/page/posts.rb, tests/document/finder.rb, tests/page/info.rb, tests/page/post.rb, tests/page/posts.rb
The changes in this PR will hopefully make the code less resilient to change and adaptable to different country needs.
- There was some repetition in the posts, post and info pages that suggested that there was another class hiding inside of them. The repetition was extracted into a class that contains all the logic for searching documents with a certain name in a certain directory.
- By doing this the dependency on `MarkdownWithFrontmatter` is now in one single class (the `Finder` class) instead of spread across all page classes. Changes to `MarkdownWithFrontmatter` affect only the `Finder` class.
- As a consequence, now the presenters contain only the logic for the views and no extra dependencies. They depend on an abstraction that responds to the relevant messages and have a single …
=> Extract a finder class to hold the logic for finding a file

lib/document/frontmatter_parser.rb, lib/document/markdown_with_frontmatter.rb, tests/document/frontmatter_parser.rb, tests/document/markdown_with_frontmatter.rb
The featured field is added so that three persons can appear as featured in the front page. We do this by adding a feature field in the frontmatter of summaries, which are mapped 1-1 to persons.
=> Add featured field to the frontmatter for summaries

lib/document/frontmatter_parser.rb, lib/document/markdown_with_frontmatter.rb, lib/page/homepage.rb, tests/document/frontmatter_parser.rb, tests/document/markdown_with_frontmatter.rb, tests/page/homepage.rb, tests/test_helper.rb
This PR adds an `event_date` convenience method to documents.
The events are selected by event day. Only the events happening
in the future are shown in the homepage. This includes events
happening "today".
The events are sorted from those happening sooner to those
happening later. From those, the three soonest ones are taken.
=> Add event dates and sort events by event date in the homepage

app.rb, lib/document/exceptions.rb, lib/document/finder.rb, tests/document/finder.rb, tests/web/info.rb, tests/web/post.rb
The lib folder should be plug and play, so no files inside that folder
should be referencing anything from Sinatra. A normal exception is
raised for the case in which no files are found.
=> Remove the reference to a Sinatra exception in the finder class

.travis.yml, bin/deploy, bin/prepare-data
This renames the old bin/deploy script to bin/prepare-data, since that
was all that it did, and adds a new script, bin/deploy, which:
* Starts the Sinatra app in the background
* Crawls the pages served by the Sinatra app with recursive wget
* Kills the Sinatra app
* Renames some of the files to be palatable to GitHub pages
* Commits the scraped and renamed files and pushes them to the
shineyoureye-static repository
At the moment the URL to push to is hardcoded as the SSH-style Git URL,
since currently we're running it manually.
=> Add a deploy script that pushes to the gh-pages branch

app.rb, lib/helpers/filepaths_helper.rb, lib/helpers/settings_helper.rb, tests/test_helper.rb, tests/web/constituencies.rb, tests/web/constituency.rb, tests/web/district.rb, tests/web/districts.rb, tests/web/info.rb, tests/web/layout.rb, tests/web/person.rb, tests/web/post.rb, tests/web/posts.rb, tests/web/representatives.rb, tests/web/search.rb, tests/web/senators.rb, tests/web/states.rb
Mapit::Wrapper was being instantiated on every request that needed MapIt
data, and so new requests to the MapIt API were being made on every request
that required them. This is a waste of resources, and massively slows
down crawling the site - the fix in this commit speeds up the crawling
of the site from about 10 minutes to about 2 minutes on my laptop.
There's no advantage in 'governors', 'representatives' and 'senators'
being functions, or from 'mapit_url' and 'mappings' being helpers
(they're only used in app.rb) so these are just variables in app.rb now.
This also makes it more explicit where that data comes from.
=> Only load MapIt data once per server instance

app.rb, lib/mapit/mappings.rb, lib/mapit/wrapper.rb, tests/document/finder.rb, tests/mapit/mappings.rb, tests/mapit/wrapper.rb
The parameters to the initializer and one of the method names of
Mapit::Mappings include the area type, and limited the number of mapping
filenames used for parent-child relationships and MapIt <-> EP area IDs
mappings. There's no need for this - the class can be more generic in
its handling of these CSV files, which will make it more easily
extendable in this app and reusable for others.
This also makes the initializer argument optional, since users won't
necessarily have to supply all of them.
=> Remove area types from Mapit::Mappings

tests/web/unlinked_pages.rb
There are two pages that aren't linked from the homepage - a special
page for the crawler to start from, and a page that just serves up a
Jinja2 template for the Polling Unit search lookup app to use.
This commit adds tests that check that these pages exist and have the
content that's important on them.
=> Add tests for the content of the 'unlinked' pages

public/stylesheets/sass/_person.scss, tests/web/person.rb, views/person.erb
This tiny PR makes it more clear that the Edit button only applies to summaries and not the rest of the information in the page.
=> Make it more clear that the Edit button only applies to summaries

lib/ep/person.rb, lib/page/person.rb, tests/ep/person.rb, tests/page/person.rb, tests/web/person.rb, views/person.erb
This PR improves the person page as a previous step to having the governors in.
We have some methods in person but we are not using them in the views:
* image <-- this is not exposed anymore, as it is not used
* birth_date
* phone
* twitter
* facebook
* memberships <-- this is still exposed but not used out of EP::Person
Also, there is some unused code that can be deleted
The Facebook tests for the integration tests are commented because no senator or representative has a facebook account, but governors do, so then we will be able to fetch a governor and uncomment them.
Merge this before #83
=> Improve person

bin/deploy
Previously this script only supported pushing to the
shineyoureye-sinatra repository over SSH. This commit changes that so
that if GITHUB_ACCESS_TOKEN is set to an appropriate personal access
token in the environment that will be used to authenticate and push over
HTTPS instead. This is important so that we can use a token to enable
pushing to the repository in the context of automated deployments.
=> Use https with a GitHub personal access token if possible

README.md, app.rb, lib/mapit/wrapper.rb, lib/membership_csv/people.rb, lib/membership_csv/person.rb, tests/mapit/wrapper.rb, tests/membership_csv/people.rb, tests/membership_csv/person.rb, tests/page/person.rb, tests/page/person_interface_test.rb, tests/web/governors.rb, tests/web/person.rb, tests/web/representatives.rb, tests/web/senators.rb, views/_list_of_people.erb, views/person.erb
This PR adds a route for the list of governors and another for a governor's dedicated page.
Morph data lacks a member for the Federal Capital Territory, and so we get only 36 states as opposed to 37 from Mapit.
Also, the same region is called Nassarawa in Mapit and Nasarawa in the data coming from Morph.
List of governors, now with images! :+1: 
Governor page, with url using ids:
Fixes https://github.com/theyworkforyou/shineyoureye-sinatra/issues/35
GitHub is showing the commits in the wrong order
Merge after #83 and before #88
=> List of governors

README.md
This PR upates the tests section of the README to remember to do `bin/prepare-data COMMIT` before running the tests.
=> Update README: remind to checkout prose commit before running tests

lib/ep/person.rb, lib/membership_csv/person.rb, tests/ep/person.rb, tests/membership_csv/person.rb, tests/web/constituency.rb, tests/web/district.rb, tests/web/governors.rb, tests/web/person.rb, tests/web/representatives.rb, tests/web/senators.rb, tests/web/state.rb, views/_list_of_people.erb, views/person.erb
Party links are showing a 404 at the moment. Since there is no trace in the requirements document that party pages have to be implemented, I think it may be better to remove this code.
Fixes https://github.com/theyworkforyou/shineyoureye-sinatra/issues/68
=> Remove party links

.travis.yml, bin/prepare-data
Fix a bug with the deploy script that was referring to an unexisting variable.
=> Bugfix deploy script

app.rb, lib/document/finder.rb, lib/ep/people_by_legislature.rb, lib/featured_person.rb, lib/helpers/filepaths_helper.rb, lib/membership_csv/people.rb, lib/page/homepage.rb, tests/document/finder.rb, tests/ep/people_by_legislature.rb, tests/featured_person.rb, tests/membership_csv/people.rb, tests/page/homepage.rb, tests/web/homepage.rb, views/homepage.erb
This PR removes the hardcoded people in the homepage and replaces it with the featured people calculated as that who has a featured field set to true in their summary.
The governor is hardcoded for now, until we have summaries for the governors.
Closes https://github.com/theyworkforyou/shineyoureye-sinatra/issues/46
Merge after #99
=> Featured people in the homepage

app.rb, lib/ep/people_by_legislature.rb, lib/membership_csv/people.rb, lib/page/place.rb, tests/ep/people_by_legislature.rb, tests/membership_csv/people.rb, tests/page/place.rb, tests/shared_examples/people_interface_test.rb, tests/web/constituency.rb, views/place.erb
This PR generalizes the three place routes that we had into a single one so that we always map the right type of people to the corresponding type of place.
Thanks to this fix, now the child places show their legislature name correctly.
Also there was some logic in the view for showing the legislature name that was moved to its page so that it can be properly tested.
Finally, after simplifying the place routes, the check for no people in an area is not needed anymore, so it was removed from the people API.
Fixes https://github.com/theyworkforyou/shineyoureye-sinatra/issues/102
=> Change the way we check for place type

app.rb, lib/mapit/geometry.rb, tests/mapit/geometry.rb
This PR adds a user agent header to GET requests to Mapit geometry.
This is done to avoid reaching the "Rate limit exceeded" when
running the deploy script, since it has to hit the Mapit API
for all the areas of the site in a very short span of time.
The `MAPIT_USER_AGENT` environment variable was set in Travis.
=> Set mapit user agent

bin/deploy
WGET_EXIT_CODE was being set in a subshell (the open bracket and close
bracket create a subshell) so wasn't available at the top level of the
script. This commit fixes that.
=> Fix a bug where WGET_EXIT_CODE was always unset

bin/deploy
This means, for example, that getting a 4xx or 5xx error from any
page when crawling the Sinatra site will cause an error and not
deploy the site. This is good, because we should be investigating
and fixing any such errors.
This is related to: https://github.com/theyworkforyou/shineyoureye-prose/pull/13 which
makes sure we're emailed on such failures.
Fixes #95
=> Only deploy the site if the wget crawl succeeded

Gemfile, Gemfile.lock, app.rb, lib/ep/people_by_legislature.rb, lib/ep/person.rb, lib/membership_csv/people.rb, lib/membership_csv/person.rb, tests/ep/people_by_legislature.rb, tests/ep/person.rb, tests/membership_csv/people.rb, tests/membership_csv/person.rb, tests/page/people.rb, tests/page/person.rb, tests/page/places.rb, tests/shared_examples/person_interface_test.rb
This PR prepares the code for using Pombola slugs instead of person ids in person-page routes.
The site specific identifier scheme (`'shineyoureye'` in this case) had to be passed as an argument to both person and people classes.
A slug method was added to EP persons. If there is no `identifier__shineyoureye` column in a CSV source or if there is no identifier with a `shineyoureye` scheme in the EP person data, the name is downcased and dashified.
=> Clean before person slugs

bin/deploy
If the deploy script tried to start the Sinatra server, but it
immediately failed (e.g. because the bundle wasn't installed correctly)
the deploy script used to just get stuck at "Waiting for Sinatra to
start..."  This change fixes that - instead it will break from the loop
that waits for the server to start if it detects that the server process
has died.
=> bin/deploy: Detect if the Sinatra server startup fails

views/redirect.erb
Since this site is hosted as static files on GitHub pages, we can't
return proper HTTP 301 / 302 redirects. However, we still want some
mechanism to redirect to new page locations so that we don't break
bookmarks or search engine results that still point to the old site.
The old technique of adding the <meta http-equiv="refresh"> tag to
the <head> of a document still works, however, and Google and other
search engines will also use this to indicate that the resource
location has changed.
This commit only adds a simple view for returning such
pseudo-redirects; it's not used anywhere yet. You would use it
in app.rb in the following way:
get '/redirect-me' do
@redirect_to = '/somewhere-else.html'
erb :redirect, layout: false
end
=> Add a view to do a pseudo-redirect with <meta http-equiv="refresh" ..>

app.rb, tests/web/event.rb, tests/web/events.rb, views/_footer.erb, views/_main_menu.erb, views/homepage.erb, views/scraper_start_page.erb
In order to serve the site, we run the Sinatra app and then wget it
and push it to a gh-pages branch, so that it is served as a static site.
The event list page at `/info/events` works when running the app
locally, but it throws a 404 once we wget it and serve it as static.
This is because the route /info/events (the event list page) is scraped
first by wget, creating an HTML file info/events.html. Later the route
/info/events/EVENT_SLUG is scraped, and wget replaces info/events.html
with an info/events directory containing a EVENT_SLUG.html file.
In other words, the index page is saved and then deleted by wget.
To solve this, we are making the URL path for an individual event
look like /events/EVENT_SLUG instead of /info/events/EVENT_SLUG.
Closes #48
=> Rewrite the event routes so that they work as the blog ones

bin/deploy
Previously this would only push to the [shineyoureye-static](https://github.com/theyworkforyou/shineyoureye-static) repository,
which will be served up as the production site.  Now it allows you to
choose between:
* Only building, not pushing: `bin/deploy --only-build`
* Building and pushing to staging: `bin/deploy staging`
* Building and pushing to production: `bin/deploy production`
(There's a new repository for the staging site called
[shineyoureye-static-staging](https://github.com/theyworkforyou/shineyoureye-static-staging), which is pushed to in the second case.)
This commit also changes the behavior so that:
* You get a better usage method if you don't choose one of those
options.
* Now you don't get spurious output about which repository URLs
will be used if you're using …
=> Allow bin/deploy to push to either staging or production repositories

lib/page/place.rb, tests/page/place.rb, tests/web/constituency.rb, tests/web/district.rb, tests/web/state.rb, views/place.erb
This PR removes some code that was a placeholder or that we are not going to use in the future but was there because the old Pombola site had it in place.
=> Simplify place pages

lib/document/finder.rb, tests/document/finder.rb
This is done so that the featured people are predictable,
since you could get test failures if you get the featured
summaries in a random order (the test data currently has
more than one representative with the featured field set
to true).
=> Sort the filenames in the document finder

app.rb, tests/web/contact.rb, tests/web/person.rb, tests/web/place.rb, tests/web/unlinked_pages.rb, views/scraper_start_page.erb
This PR redirects the old routes that no longer exist in the new version of the site according to [this list](https://gist.github.com/mhl/02324e71cb3aa36650444a909b6776a4).
Merge after #143
=> Add redirects for the old routes

tests/document/markdown_parser.rb
This was left by Friday's refactoring :smile:
=> Delete line causing Rubocop Style/EmptyLinesAroundBlockBody error

app.rb, lib/ep/people_by_legislature.rb, lib/factory/person.rb, lib/membership_csv/people.rb, tests/ep/people_by_legislature.rb, tests/factory/person.rb, tests/membership_csv/people.rb, tests/page/people.rb, tests/page/places.rb, tests/test_doubles.rb
This PR introduces a person factory to deal with person creation without coupling the created classes with the classes that create them, so that if the interface changes in the future, the changes don't cascade through the entire codebase.
Closes #123
=> Add a person factory

public/stylesheets/sass/_homepage.scss, views/homepage.erb
The code was taken from the Pombola version of the site.
Poll is placed between "News" and "Events". If there are no events, the "Events" column is hidden.
When there are no events:
When there are events:
Closes https://github.com/theyworkforyou/shineyoureye-sinatra/issues/150
(Screenshots by @zarino :slightly_smiling_face: )
=> Add a PollDady poll to the front page

.github/CONTRIBUTING.md, Gemfile, Gemfile.lock, app.rb, bin/deploy, data/extra-slugs.csv, lib/checks.rb, lib/ep/people_by_legislature.rb, lib/ep/person.rb, lib/membership_csv/people.rb, lib/membership_csv/person.rb, lib/people_slug_to_person.rb, lib/person_slug.rb, tests/ep/people_by_legislature.rb, tests/ep/person.rb, tests/membership_csv/people.rb, tests/membership_csv/person.rb
This PR is needed because there was a bug in the `slug_to_person` method, that made us loose a person if they had the same slug as another person whose name was coming later in the alphabet.
This is because of how we were storing the slugs as keys. Now, before storing them, a check is made to ensure that
1) a slug exists
2) the slug is unique
if one of these requirements is not met, an error is raised, so that we fix the slugs upstream.
The tribal knowledge section of the contributing guide was updated to explain this.
Closes #162 
At the moment, there are persons with no slugs, so the integration tests are failing, until these persons are added a slug.
[This spreadsheet ](https://docs.google.com/spreadsheets/d/18DGJ2NpZbwmUfmod9veIK1IFht9xTEonRq0fASxfoR4/edit#gid=0)contains slug …
=> Fix slug_to_person method's bug

app.rb, lib/document/markdown_with_frontmatter.rb, tests/document/finder.rb, tests/document/markdown_with_frontmatter.rb
We found a problem with the site which occurs in the following
situation:
- Someone creates a new post in prose.io. (That creates a file
in the repository with a filename baseed on slug of the post
which is based on its title. The slug is stored in the post's
YAML frontmatter as well.)
- Someone edits the title of the post in prose.io. This changes
the slug which is stored in the YAML frontmatter, but not the
filename in the repository.)
In our code what was happening is that any list of multiple posts
(e.g. on the front page) would generate links based on the slug
in the YAML frontmatter. However, when looking up an individual
post for display, the slug in the URL is used to form a glob
pattern to find in the appropriate directory in the repository.
This means that changes in the title …
=> Editing the title of a blog post should not make it 404

views/_header.erb, views/search.erb
We've had a report that the search buttons aren't working on mobile. We think this is because the buttons had `type="button"` rather than `type="submit"` on them.
This fix changes them to be proper submit buttons, which in my testing makes them work as expected.
Fixes #170
=> Change search buttons to use type="submit"

views/homepage.erb
Fixes #175.
Removes the 1-tweet limit from the homepage Twitter widget, meaning it now displays the entire Twitter timeline, in a scrollable container.
=> Scrollable Twitter feed on homepage

lib/mapit/place.rb, tests/mapit/place.rb
This makes it easier to get the state for an area, without having to worry about what kind of area you're dealing with. This should make it easier to do https://github.com/theyworkforyou/shineyoureye-sinatra/issues/117, which needs to group people by state.
Fixes https://github.com/theyworkforyou/shineyoureye-sinatra/issues/195
=> Add Mapit::Place#state method

lib/page/homepage.rb, public/stylesheets/sass/_homepage.scss, tests/page/homepage.rb, views/homepage.erb
The space freed up by removing the poll allows us to spread the blog posts across two columns.
Fixes #181.
=> Remove Polldaddy poll from homepage

public/javascripts/multipurpose-search.js, views/_footer.erb, views/_header.erb, views/search.erb
Client-side handling of generic search terms, in the "PU number" search box, via Google Custom Search.
Fixes #113.
`009849292720701569670:dnm2ccnvkai` is the ID of the Custom Search Engine I had to create to get it working. Annoyingly, it doesn’t seem possible to create these under an "organisational" account, only a personal one. So right now it’s "owned" by my @mysociety.org Google account. I can invite other Google accounts as administrators, but they won’t be able to invite more users. I wonder whether there’s a better account we should be storing this CSE under?
=> Enable general site search, not just PU number lookups

public/stylesheets/sass/_bootstrap.scss, public/stylesheets/sass/_homepage.scss, tests/web/homepage.rb, views/homepage.erb
Putting the blog posts and video into a single column means the twitter timeline can be much taller, beside the two of them, rather than being limited to the height of the video alone.
This commit also makes the height of the video responsive to its width, so it looks more natural on medium and small screens.
Fixes #180.
=> Combine blog and social sections on homepage

public/stylesheets/sass/_forms.scss, public/stylesheets/sass/_homepage.scss, public/stylesheets/sass/_site-header.scss, views/homepage.erb, views/search.erb
Fixes #183. Avoids the duplication of the header search box and the "Find your Representative" button on the homepage.
Also, while I was there, I improved the vertical spacing on the search results page, so the form doesn’t appear so far from the top of the page.
=> Homepage search box

.rubocop.yml
Every time you do a deploy a static version of the site is added to the `builds/` directory. Over time this directory becomes huge and contains loads of files. When Rubocop runs it scans all files looking for ones that look like Ruby files. This means that Rubocop takes ages to start when you have a big builds/ directory. So to fix this just tell Rubocop to ignore everything in that directory.
I've also ignored the vendor directory to avoid failures on Travis. See the commit message for more details.
=> Tell Rubocop to ignore builds/ directory

.rubocop.yml, .travis.yml, Gemfile, Gemfile.lock, README.md, bin/build_summaries.rb
The current version of Ruby, 2.3.1, is "In security maintenance phase (will EOL soon!)", so upgrade to the newest available stable version of Ruby.
I had to update Webmock as well because the version we were on is incompatible with Ruby >= 2.4, see bblimke/webmock#683.
Fixes https://github.com/theyworkforyou/shineyoureye-sinatra/issues/203
=> Upgrade Ruby to 2.5.3

Gemfile
I had to update the version of Ruby in `.travis.yml` in the shineyoureye-prose repo to reflect the Ruby version bump in this repo in https://github.com/theyworkforyou/shineyoureye-prose/commit/2223ef882e4bd4455886074afdebedf5f5fb86a3. Update the docs to mention that.
=> Need to change sye-prose when updating Ruby version

tests/web/person.rb, views/person.erb
Our partners have told us that having this as a link is confusing because their mail client isn't setup properly, so it doesn't work as expected.
They originally asked us if we could add a contact form to this page, but that's going to take a lot of time and add a lot of complexity. So as an alternative solution we're simply making the email plain text, which makes it easier to simply copy/paste it into your email client.
Fixes #187 
---
=> Make email on politician profile plain text

app.rb, lib/page/homepage.rb, public/javascripts/show-random-child.js, tests/page/homepage.rb, tests/web/homepage.rb, views/homepage.erb
Each time the site is rebuilt, 10 representatives of each type are randomly selected for inclusion on the homepage.
The details of all 30 representatives are baked into the markup of the homepage, but only the first representative in each of these groups is actually made _visible_ to website visitors, by default.
We then use JavaScript to randomly select one representative from each group, to show.
The end result is that, in browsers with JavaScript support, each time the homepage is loaded, it will give the _effect_ of a random selection of representatives being shown. But in actuality, there are only 10 possible reps in each group.
We’re hoping 10 will be a good balance of "freshness" versus HTML markup bloat – but we can easily increase the number if Yemi / Seun feel the same few faces …
=> Show random people of each type on homepage
